site_name: Sachin Tiwari
site_url: https://sachintiwari.netlify.app/
site_author: Sachin Tiwari
site_description: A website showcasing my skills, experience, and projects.
nav:
  - Home: index.md
  - Experience: experience.md
  - Skills & Tech-stack: skills.md
  - Projects Undertaken: projects.md
  - Education: education.md
  - Rewards & Recognitions: recognition.md
  - Interests & Hobbies: interests.md
  - About Me: about.md
  - Downloads: download.md
theme:
  features:
    - navigation.tracking
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.tabs.link
  favicon: images/favicon_new.png
  icon:
    logo: material/signature-freehand
  language: en
  font:
    text: Google Sans
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  scheme: default
  primary: indigo
  accent: indigo

extra:
  generator: false

  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/classicaldobby
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sachintiwari2058
    - icon: fontawesome/brands/github
      link: https://github.com/sachint2202
    - icon: fontawesome/brands/medium
      link: https://medium.com/@sachintiwari2
    - icon: fontawesome/solid/paper-plane
      link: mailto:<sachintiwari2058@gmail.com>

copyright: Copyright &copy; 2025 &nbsp;Sachin Tiwari

extra_css:
  - stylesheets/extra.css # or wherever your CSS lives
markdown_extensions:
  - tables
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - tags
  #- social
